// <auto-generated />
namespace WST.DB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _89ii : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_89ii));
        
        string IMigrationMetadata.Id
        {
            get { return "201712120131055_89ii"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
